-- TRAE 거래소 데이터 스키마 (Supabase / Postgres)
-- 요구사항: 모든 테이블명은 반드시 `trae_` prefix 사용
-- 사용법: Supabase SQL Editor에 그대로 붙여 넣고 실행
-- 주의: 운영에서는 RLS/정책을 환경에 맞게 추가하세요. (service role로만 접근할 경우 RLS 없이도 가능)

create table if not exists public.trae_users (
  id bigint primary key,
  username text not null unique,
  password_hash text not null,
  role text not null,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);

create table if not exists public.trae_balances (
  user_id bigint primary key,
  usdt double precision not null default 0
);

create table if not exists public.trae_positions (
  id bigint primary key,
  user_id bigint not null,
  symbol text not null,
  side text not null,
  qty double precision not null,
  entry_price double precision not null,
  leverage integer not null,
  margin double precision not null,
  created_at timestamptz not null
);

create table if not exists public.trae_trades (
  id bigint primary key,
  user_id bigint not null,
  symbol text not null,
  side text not null,
  qty double precision not null,
  entry_price double precision not null,
  exit_price double precision not null,
  leverage integer not null,
  pnl double precision not null,
  created_at timestamptz not null
);

create table if not exists public.trae_profit_cards (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  trade_id bigint not null,
  title text not null,
  note text not null default '',
  created_at timestamptz not null
);

create table if not exists public.trae_user_settings (
  user_id bigint primary key,
  trade_percent integer not null default 50,
  trade_leverage integer not null default 100,
  chart_prefs jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null
);

create index if not exists trae_positions_user_id_idx on public.trae_positions(user_id);
create index if not exists trae_trades_user_id_idx on public.trae_trades(user_id);
create index if not exists trae_profit_cards_user_id_idx on public.trae_profit_cards(user_id);
