-- 앱 메인 DB(회원/잔고/포지션/거래) - Supabase(Postgres)용
-- 주의: 서버에서 쓰기/읽기 하려면 보통 service role key를 사용합니다.
-- 이 스크립트는 테이블만 만들고, RLS 정책은 환경에 맞게 설정하세요.

create table if not exists public.app_users (
  id bigint primary key,
  username text not null unique,
  password_hash text not null,
  role text not null,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);

create table if not exists public.app_balances (
  user_id bigint primary key,
  usdt double precision not null default 0
);

create table if not exists public.app_positions (
  id bigint primary key,
  user_id bigint not null,
  symbol text not null,
  side text not null,
  qty double precision not null,
  entry_price double precision not null,
  leverage integer not null,
  margin double precision not null,
  created_at timestamptz not null
);

create table if not exists public.app_trades (
  id bigint primary key,
  user_id bigint not null,
  symbol text not null,
  side text not null,
  qty double precision not null,
  entry_price double precision not null,
  exit_price double precision not null,
  leverage integer not null,
  pnl double precision not null,
  created_at timestamptz not null
);

create table if not exists public.app_profit_cards (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  trade_id bigint not null,
  title text not null,
  note text not null default '',
  created_at timestamptz not null
);

create table if not exists public.app_user_settings (
  user_id bigint primary key,
  trade_percent integer not null default 0,
  trade_leverage integer not null default 20,
  updated_at timestamptz not null
);

create index if not exists app_positions_user_id_idx on public.app_positions(user_id);
create index if not exists app_trades_user_id_idx on public.app_trades(user_id);

