-- TRAE 거래소 데이터 스키마 (Supabase / Postgres) - v2
-- 목적:
-- 1) 배포 환경에서 SQLite를 쓰지 않고 Supabase에 "회원/잔고/설정/포지션/거래/세션"을 모두 저장
-- 2) 가입/로그인 후 세션도 Supabase에 저장하여 서버리스 배포에서도 로그인 상태 유지
--
-- 사용법:
-- 1) Supabase 프로젝트 → SQL Editor → New query
-- 2) 아래 SQL 전체 실행
--
-- 주의:
-- - 운영에서는 RLS/정책을 환경에 맞게 추가하세요.
-- - 이 프로젝트는 서버에서 Service Role Key로 접근하는 구조라, RLS를 켠 경우 정책이 없으면 동작하지 않습니다.

-- ===== core tables (trae_ prefix) =====
create table if not exists public.trae_users (
  id bigint primary key,
  username text not null unique,
  password_hash text not null,
  role text not null,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);

create table if not exists public.trae_balances (
  user_id bigint primary key,
  usdt double precision not null default 0
);

create table if not exists public.trae_positions (
  id bigint primary key,
  user_id bigint not null,
  symbol text not null,
  side text not null,
  qty double precision not null,
  entry_price double precision not null,
  leverage integer not null,
  margin double precision not null,
  created_at timestamptz not null
);

create table if not exists public.trae_trades (
  id bigint primary key,
  user_id bigint not null,
  symbol text not null,
  side text not null,
  qty double precision not null,
  entry_price double precision not null,
  exit_price double precision not null,
  leverage integer not null,
  pnl double precision not null,
  created_at timestamptz not null
);

create table if not exists public.trae_profit_cards (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  trade_id bigint not null,
  title text not null,
  note text not null default '',
  created_at timestamptz not null
);

create table if not exists public.trae_user_settings (
  user_id bigint primary key,
  trade_percent integer not null default 50,
  trade_leverage integer not null default 100,
  chart_prefs jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null
);

-- 세션(서버리스 배포에서도 로그인 유지)
create table if not exists public.trae_sessions (
  token text primary key,
  user_id bigint not null,
  created_at timestamptz not null,
  expires_at timestamptz not null
);

create index if not exists trae_positions_user_id_idx on public.trae_positions(user_id);
create index if not exists trae_trades_user_id_idx on public.trae_trades(user_id);
create index if not exists trae_profit_cards_user_id_idx on public.trae_profit_cards(user_id);
create index if not exists trae_sessions_user_id_idx on public.trae_sessions(user_id);
create index if not exists trae_sessions_expires_at_idx on public.trae_sessions(expires_at);

-- ===== optional logging tables (used by server/utils/supa-log.ts) =====
-- 없으면 그냥 경고 로그만 남고 서비스 기능에는 영향 없지만, 운영 편의상 같이 만들어두는 걸 권장

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  local_user_id bigint,
  username text,
  role text,
  created_at timestamptz not null
);

create table if not exists public.app_login_events (
  id bigint generated by default as identity primary key,
  local_user_id bigint,
  username text,
  area text not null,
  success boolean not null,
  ip text,
  user_agent text,
  created_at timestamptz not null
);

create table if not exists public.app_buys (
  id bigint generated by default as identity primary key,
  local_user_id bigint not null,
  symbol text not null,
  side text not null,
  buy_time timestamptz not null,
  buy_price double precision not null,
  qty double precision not null,
  margin double precision not null,
  leverage integer not null,
  total_usdt double precision not null
);

create table if not exists public.app_admin_credits (
  id bigint generated by default as identity primary key,
  admin_local_user_id bigint not null,
  target_local_user_id bigint not null,
  amount double precision not null,
  created_at timestamptz not null
);

